export const tools = [
  {
    id: 'bg-remover',
    name: 'Background Remover',
    shortName: 'Remove BG',
    route: '/tools/bg-remover',
    legacyPath: '/tools/bg-remover.html',
    icon: 'auto_fix_high',
    accent: 'red',
    description: 'Remove image backgrounds locally in the browser.',
  },
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    shortName: 'Merge PDFs',
    route: '/tools/merge-pdf',
    legacyPath: '/tools/merge-pdf.html',
    icon: 'picture_as_pdf',
    accent: 'orange',
    description: 'Combine multiple PDF files into a single document.',
  },
  {
    id: 'file-converter',
    name: 'File Converter',
    shortName: 'Convert Files',
    route: '/tools/file-converter',
    legacyPath: '/tools/file-converter.html',
    icon: 'sync_alt',
    accent: 'cyan',
    description: 'Convert files without sending them to a server.',
  },
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    shortName: 'Compress Images',
    route: '/tools/image-compressor',
    legacyPath: '/tools/image-compress.html',
    aliases: ['/tools/image-compress'],
    icon: 'compress',
    accent: 'green',
    description: 'Reduce image file size while keeping quality in control.',
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    shortName: 'Compress PDF',
    route: '/tools/compress-pdf',
    legacyPath: '/tools/compress-pdf.html',
    icon: 'data_saver_on',
    accent: 'yellow',
    description: 'Optimize PDF documents for smaller file sizes.',
  },
  {
    id: 'scan-to-pdf',
    name: 'Scan to PDF',
    shortName: 'Scan PDF',
    route: '/tools/scan-to-pdf',
    legacyPath: '/tools/scan-to-pdf.html',
    icon: 'document_scanner',
    accent: 'purple',
    description: 'Turn scans and images into polished PDF files.',
  },
  {
    id: 'add-image-pdf',
    name: 'Add Image to PDF',
    shortName: 'Add Image',
    route: '/tools/add-image-pdf',
    legacyPath: '/tools/add-image-pdf.html',
    icon: 'add_photo_alternate',
    accent: 'ink',
    description: 'Place images into PDF documents.',
  },
];

export function getToolByRoute(pathname) {
  return tools.find((tool) => tool.route === pathname || tool.aliases?.includes(pathname));
}
